### ISSUE TITLE
Allow mapping functions to return Promise<'T>

### ISSUE THREAD

**Issue by Zaid-Ajaj** [ful-stackz/fetch-gql#1]
Suppose you have an instance of a `GraphQLResponse<Data>`, allow the mapping functions `ok`, `error` etc. to make asynchronous calls that can be awaited too. So that:
```ts
export type GraphQLResponse<TData, TError> = {
    match: <T>(config: {
      ok: (data: TData) => T;
      err: (errors: TError[]) => T;
    }) =>T;
}
```
Becomes:
```ts
export type GraphQLResponse<TData, TError> = {
    match: <T>(config: {
      ok: (data: TData) => T | Promise<T>;
      err: (errors: TError[]) => T | Promise<T>;
    }) =>T | Promise<T>;
}
```
> Not sure about the overloaded syntax above, you get the idea. At runtime, you might need to check whether you have an instance of a Promise or any other value. In which you would have to await it internally too

This way, you will be able to `await` the `match` call to get more data:
```ts
const userResponse = await client.query<GetUserQuery, GetUserQueryVariables>({
  query: getUserQuery,
  variables: { id: 1 } // type checked agains GetUserQueryVariables
})

const userData = await userResponse.match({
  ok: async(data) => { 
    const { user } = data;
    return await client.query<AnotherQuery, GetDataVariables>({ token: user.token });
  },
  err: errors => {
    console.log(errors);
     /* TODO: construct here a GraphQL response that has errors */
    return errors; 
  }
});
```

**Comment by ful-stackz** [comment]
Thanks for the suggestion! Your example at the end:

> ```typescript
> const userResponse = await client.query<GetUserQuery, GetUserQueryVariables>({
>   query: getUserQuery,
>   variables: { id: 1 } // type checked agains GetUserQueryVariables
> })
> 
> const userData = await userResponse.match({
>   ok: async(data) => { 
>     const { user } = data;
>     return await client.query<AnotherQuery, GetDataVariables>({ token: user.token });
>   },
>   err: errors => {
>     console.log(errors);
>      /* TODO: construct here a GraphQL response that has errors */
>     return errors; 
>   }
> });
> ```

is perfectly valid in the already existing API! Since `.match()` returns a generic type `<T>` in the described use case that generic type becomes `T => Promise<GraphQLResponse<AnotherQuery, GraphQLError>>`.

However the pain point lies in the `err` handler - you need to return an object of the same `Promise<GraphQLResponse<AnotherQuery, GraphQLError>>` shape, which is not easy to do, since there is no exposed function which does that and constructing one yourself goes against the simplistic nature of the library.

Therefore I've come up with another API to deal with sequential, if you will, requests. It allows you to make a request using the data from a previous one, without 'unfolding' the first (example probably makes more sense than words 😄).

Presenting the new `.andThen()` API:

```typescript
type GraphQLResponse<TData, TError> = {
  andThen: <T, E>(
    config: {
      action: (data: TData) => Promise<GraphQLResponse<T, E>>,
      mapErr: (errors: E[]) => TError[]
    } | {
      action: (data: TData) => Promise<GraphQLResponse<T, TError>>
    }
  ) => Promise<GraphQLResponse<T, E>>;  
}
```

When using in the context of a single GraphQL client (or clients that work with the same error type) 'chaining' requests looks like this:

```typescript
const client = createClient({ url: '' })
const login = await client.query<LoginMutation, LoginMutationVariables>({ /* mutation config */ })
const user = await login.andThen({
  action: data => client.query<UserQuery, UserQueryVariables({
    query: '',
    variables: { token: data.token }
  })
})

user.match({
  ok: data => { }, // data is of type UserQuery
  err: errors => { } // errors is of type GraphQLError[] (default error type)
})
```

When using in the context of multiple GraphQL clients that work with different error types the `.andThen()` requires another field `mapErr` to map the error of the second request to the error type of the original request. The error handling is a really troublesome part here and this solution was the better one I could come up with. Example:

```typescript
const regularErrClient = createClient({ url: '' })

type CustomError = { code: number; message: string }
const customErrClient = createClient<CustomError>({ url: '' })

const login = await regularErrClient.query<LoginMutation, LoginMutationVariables>({ /* query config */ })
const user = await login.andThen({
  action: data => customErrClient.query<UserQuery, UserQueryVariables>({
    query: '',
    variables: { token: data.token }
  }),
  mapErr: errors => errors.map(e => ({ /* map CustomError to GraphQLError */ }))
}) 

user.match({
  ok: data => { }, // data is of type UserQuery
  err: errors => { } // errors is of type GraphQLError[]
})
```

I am not sure whether it's more usable to map the errors of the second query to the error type of the first, or the other way around, but in any case the errors need to be mapped in order to get a monadic(ish) response type.

Would love to hear what you think about that 😊

**Comment by Zaid-Ajaj** [comment]
The `.andThen` function is kind of what I was looking for here 🎉 I am bit on the fence with respect to the `mapErr` function but I also don't have a better solution for it

**Comment by ful-stackz** [comment]
Bottom line is (for me) most of the times you'll be using a single GraphQL client in the whole application, so you'll never have to touch the `mapErr` part. In the very few cases where you do use multiple clients - it's not the perfect solution, but hey you get _some_ type checking while not going _too much_ out of your way. Win-win, right 😄
